url: https://mgaynor1.github.io

# Site settings
title: Michelle Gaynor
email: MichelleGaynor@knights.ucf.edu
description: "Evolutionary Biology"

# Color settings (hex-codes without the leading hash-tag)
color:
  link: CBA72B
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: git
    url: http://github.com/
  - title: envelope
    url: mailto:
  - title: google
    url: http://scholar.google.com/

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
theme: jekyll-theme-cayman
