# Site settings
title: Michelle L. Gaynor
email: michellegaynor@knights.ucf.edu
url: https://mgaynor1.github.io
author: Shelly Gaynor

# Color settings (hex-codes without the leading hash-tag)
color:
  link: 0021a5
  primary: fa4616
  secondary: fa4616
  secondary-dark: 000
  dark: 000

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/shellygaynor
  - title: google scholar 
    url: http://scholar.google.com/citations?user=WlPwalgAAAAJ&hl=en
  - title: github
    url: https://github.com/mgaynor1
  - title: researchgate
    url: https://www.researchgate.net/profile/Michelle_Gaynor2?ev=hdr_xprf&_sg=SF6w0e8JbkH3qCQSvKcNqhItfg8K4480WJQXigcRfnnh2jerD6pB1M2ruOVwhMZXunStmEE00tZtegr02CEFoMOf


# Build settings
markdown: kramdown
permalink: pretty

##Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-twitter-plugin
