url: https://mgaynor1.github.io

# Site settings
title: Michelle L. Gaynor
email: michellegaynor@ufl.edu
description: "Michelle L. Gaynor, PhD Student"

# Color settings (hex-codes without the leading hash-tag)
color:
  link: CBA72B
  primary: fed136
  secondary: fec503 
  secondary-dark: 000

# Team names, titles and social links
people:
- name: 
  pic: 1
  position: 
  social:
    - title: 
      url: 

- name: 
  pic: 2
  position: 
  social:
    - title: 
      url: 

- name: 
  pic: 3
  position: 
  social:
    - title: 
      url: 
      
- name: 
  pic: 4
  position: 
  social:
    - title: 
      url: 
      
- name: 
  pic: 5
  position: 
  social:
    - title: 
      url: 
      
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/shellygaynor
  - title: git
    url: http://github.com/mgaynor1
  - title: envelope
    url: mailto:michellegaynor@ufl.edu
  - title: google
    url: http://scholar.google.com/citations?user=WlPwalgAAAAJ&hl=en

# Postal address (add as many lines as necessary)
address:
  - line: Updating
  - line: soon

# Build settings
markdown: kramdown
permalink: pretty